name: CI/CD for Todo App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      # Opcional: sube el build del frontend al backend/public si sirven desde el mismo lugar
      - name: Copy frontend build to backend
        run: |
          cp -r frontend/dist backend/public

      # Opcional: comandos de pruebas o lint aquí
      # - name: Run tests
      #   working-directory: ./backend
      #   run: npm test

      # 🚀 Aquí iría tu paso de deploy (ej: Render, Railway, etc.)
